# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-24 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentWindowData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteId', models.IntegerField()),
                ('url', models.CharField(max_length=2000)),
                ('stateLabel', models.CharField(max_length=200)),
                ('cwCount', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ContentWindowRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(blank=True, max_length=300, null=True)),
                ('hashId', models.CharField(max_length=300, unique=True)),
                ('Browser', models.CharField(blank=True, default='Chrome', max_length=300, null=True)),
                ('BrowserVersion', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventFireCountData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteId', models.IntegerField()),
                ('url', models.CharField(max_length=2000)),
                ('stateLabel', models.CharField(max_length=200)),
                ('tag_name', models.CharField(max_length=200)),
                ('event_order', models.CharField(max_length=1000)),
                ('event_count', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='EventFireCountRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(blank=True, max_length=300, null=True)),
                ('hashId', models.CharField(max_length=300, unique=True)),
                ('Browser', models.CharField(blank=True, default='Chrome', max_length=300, null=True)),
                ('BrowserVersion', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostMessageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteId', models.IntegerField()),
                ('url', models.CharField(max_length=2000)),
                ('stateLabel', models.CharField(max_length=1000)),
                ('openType', models.CharField(choices=[('0', 'frame'), ('1', 'window')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PostMessageDataElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('messageData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='logmain.PostMessageData')),
            ],
        ),
        migrations.CreateModel(
            name='PostMessageRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(blank=True, max_length=300, null=True)),
                ('hashId', models.CharField(max_length=300, unique=True)),
                ('Browser', models.CharField(blank=True, default='Chrome', max_length=300, null=True)),
                ('BrowserVersion', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='postmessagedata',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postMessages', to='logmain.PostMessageRun'),
        ),
        migrations.AddField(
            model_name='eventfirecountdata',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='logmain.EventFireCountRun'),
        ),
        migrations.AddField(
            model_name='contentwindowdata',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='logmain.ContentWindowRun'),
        ),
    ]
