# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-29 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logmain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSPData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteId', models.IntegerField()),
                ('targetURL', models.CharField(max_length=2000)),
                ('stateLabel', models.CharField(max_length=200)),
                ('tagName', models.CharField(max_length=300)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csp_datas', to='logmain.ContentWindowRun')),
            ],
        ),
        migrations.CreateModel(
            name='CSPDataViolatedURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violatedURL', models.CharField(max_length=2000)),
                ('CSPData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violated_urls', to='logmain.CSPData')),
            ],
        ),
        migrations.CreateModel(
            name='CSPRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(blank=True, max_length=300, null=True)),
                ('hashId', models.CharField(max_length=300, unique=True)),
                ('Browser', models.CharField(blank=True, default='Chrome', max_length=300, null=True)),
                ('BrowserVersion', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
