# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-29 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logmain', '0002_cspdata_cspdataviolatedurl_csprun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cspdata',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csp_datas', to='logmain.CSPRun'),
        ),
    ]
