# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-31 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logmain', '0003_auto_20190129_2218'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cspdata',
            unique_together=set([('run', 'siteId', 'targetURL', 'stateLabel', 'tagName')]),
        ),
    ]
