# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-05 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logmain', '0004_auto_20190131_1417'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventfirecountdata',
            unique_together=set([('run', 'siteId', 'url', 'stateLabel', 'tag_name', 'event_order', 'event_count')]),
        ),
    ]
