# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-11 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logmain', '0005_auto_20190205_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteId', models.IntegerField()),
                ('targetURL', models.CharField(max_length=2000)),
                ('stateLabel', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ScriptRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(blank=True, max_length=300, null=True)),
                ('hashId', models.CharField(max_length=300)),
                ('attackMode', models.IntegerField()),
                ('Browser', models.CharField(blank=True, default='Chrome', max_length=300, null=True)),
                ('BrowserVersion', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='contentwindowdata',
            unique_together=set([('run', 'siteId', 'url', 'stateLabel', 'cwCount')]),
        ),
        migrations.AlterUniqueTogether(
            name='scriptrun',
            unique_together=set([('hashId', 'attackMode')]),
        ),
        migrations.AddField(
            model_name='scriptdata',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_datas', to='logmain.ScriptRun'),
        ),
        migrations.AlterUniqueTogether(
            name='scriptdata',
            unique_together=set([('run', 'siteId', 'targetURL', 'stateLabel', 'message')]),
        ),
    ]
