# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-12 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logmain', '0006_auto_20190211_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptdata',
            name='messageLength',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='scriptdata',
            unique_together=set([('run', 'siteId', 'targetURL', 'stateLabel', 'message', 'messageLength')]),
        ),
    ]
