# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-19 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logmain', '0009_auto_20190313_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectReadPropertiesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteId', models.IntegerField()),
                ('url', models.CharField(max_length=2000)),
                ('stateLabel', models.CharField(max_length=200)),
                ('tag_name', models.CharField(max_length=200)),
                ('props', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectReadPropertiesRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(blank=True, max_length=300, null=True)),
                ('hashId', models.CharField(max_length=300, unique=True)),
                ('Browser', models.CharField(blank=True, default='Chrome', max_length=300, null=True)),
                ('BrowserVersion', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='objectreadpropertiesdata',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='logmain.ObjectReadPropertiesRun'),
        ),
        migrations.AlterUniqueTogether(
            name='objectreadpropertiesdata',
            unique_together=set([('run', 'siteId', 'url', 'stateLabel', 'tag_name', 'props')]),
        ),
    ]
